import { FiAlertTriangle, FiPieChart, FiAlertCircle } from "react-icons/fi";
import {
  LuInfo,
  LuMusic4,
  LuLayoutGrid,
  LuSendHorizontal,
  LuPlug,
  LuPlay,
  LuSettings,
  LuArrowUpDown,
  LuCalendar,
} from "react-icons/lu";
import { GoTriangleDown, GoTriangleUp, GoDownload } from "react-icons/go";
import { GrTransaction } from "react-icons/gr";
import {
  MdOutlineGroup,
  MdErrorOutline,
  MdOutlineLock,
  MdMailOutline,
  MdOutlineWbSunny,
  MdCandlestickChart,
  MdError,
  MdCheckCircle
} from "react-icons/md";
import {
  FaRegFolder,
  FaRegCopy,
  FaTimes,
  FaBars,
  FaUserCircle,
  FaChartLine,
  FaCalendar,
  FaChartPie,
  FaLinkedinIn,
  FaChevronDown,
} from "react-icons/fa";
import {
  HiDotsHorizontal,
  HiDotsVertical,
  HiOutlineDotsHorizontal,
  HiOutlineArrowNarrowUp,
  HiOutlineArrowNarrowDown,
} from "react-icons/hi";
import { HiBars3 } from "react-icons/hi2";
import { BiSolidBank, BiChart } from "react-icons/bi";
import { TbAlertHexagon, TbLogout2, TbUpload } from "react-icons/tb";
import { AiFillGold } from "react-icons/ai";
import { GiReceiveMoney } from "react-icons/gi";
import {
  FaAngleLeft,
  FaAngleRight,
  FaAngleDown,
  FaAngleUp,
  FaArrowUp,
  FaArrowDown,
  FaArrowRight,
  FaArrowLeft,
  FaRegCircleCheck,
  FaCheck,
  FaDollarSign,
  FaPlus,
  FaRegTrashCan,
  FaRegCircleUser,
  FaRegUser,
  FaWallet,
  FaArrowTrendUp,
  FaBitcoin,
  FaArrowTrendDown,
  FaHammer,
} from "react-icons/fa6";
import {
  RiFlashlightLine,
  RiFileListLine,
  RiTableLine,
  RiMoneyRupeeCircleFill,
  RiPencilFill,
} from "react-icons/ri";
import {
  IoCubeOutline,
  IoCube,
  IoChatboxEllipsesOutline,
  IoCloseOutline,
  IoCopyOutline,
  IoDocumentTextOutline,
  IoTimeOutline,
  IoMoonOutline,
  IoSettingsOutline,
  IoCash,
  IoReceipt,
  IoCalendarClear,
  IoGift,
} from "react-icons/io5";
import { CiCalendarDate, CiSearch } from "react-icons/ci";
import {
  IoMdEye,
  IoMdEyeOff,
  IoIosArrowDown,
  IoMdAnalytics,
} from "react-icons/io";
import { PiPencilSimpleBold, PiShootingStarBold } from "react-icons/pi";
import { DiGoogleAnalytics } from "react-icons/di";

export {
  FiAlertTriangle,
  FiPieChart,
  FiAlertCircle,
  LuInfo,
  LuMusic4,
  LuLayoutGrid,
  LuSendHorizontal,
  LuPlug,
  LuPlay,
  LuSettings,
  LuArrowUpDown,
  LuCalendar,
  GoTriangleDown,
  GoTriangleUp,
  GoDownload,
  MdErrorOutline,
  MdOutlineGroup,
  MdOutlineLock,
  MdMailOutline,
  MdCandlestickChart,
  MdCheckCircle,
  MdError,
  FaRegFolder,
  FaRegCopy,
  FaAngleLeft,
  FaAngleDown,
  FaAngleUp,
  FaAngleRight,
  FaArrowDown,
  FaArrowLeft,
  FaArrowRight,
  FaArrowUp,
  FaTimes,
  FaBars,
  FaWallet,
  FaChartLine,
  FaArrowTrendUp,
  FaArrowTrendDown,
  FaBitcoin,
  FaCalendar,
  FaHammer,
  FaChevronDown,
  RiFlashlightLine,
  IoCubeOutline,
  IoCube,
  CiCalendarDate,
  IoMdEye,
  IoMdEyeOff,
  IoChatboxEllipsesOutline,
  IoCopyOutline,
  IoDocumentTextOutline,
  IoTimeOutline,
  IoMdAnalytics,
  FaRegCircleCheck,
  FaCheck,
  IoIosArrowDown,
  IoCloseOutline,
  IoCash,
  IoReceipt,
  IoCalendarClear,
  HiDotsHorizontal,
  HiDotsVertical,
  HiOutlineDotsHorizontal,
  TbAlertHexagon,
  TbLogout2,
  TbUpload,
  FaDollarSign,
  FaPlus,
  FaRegTrashCan,
  FaRegCircleUser,
  FaRegUser,
  RiFileListLine,
  RiTableLine,
  RiMoneyRupeeCircleFill,
  PiPencilSimpleBold,
  PiShootingStarBold,
  DiGoogleAnalytics,
  GrTransaction,
  HiBars3,
  CiSearch,
  MdOutlineWbSunny,
  IoMoonOutline,
  IoSettingsOutline,
  FaUserCircle,
  BiSolidBank,
  AiFillGold,
  GiReceiveMoney,
  HiOutlineArrowNarrowUp,
  HiOutlineArrowNarrowDown,
  RiPencilFill,
  BiChart,
  IoGift,
  FaChartPie,
  FaLinkedinIn,
};
